
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: storage/development.sqlite3


# test:
#   <<: *default
#   database: storage/test.sqlite3

# production:
#   adapter: sqlite3
#   database: <%= Rails.root.join("db", "production.sqlite3") %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   port: 5432

# development:
#   <<: *default
#   database: bookshop_db_rpx0

# test:
#   <<: *default
#   database: my_app_test

# production:
#   <<: *default
#   database: bookshop_db_rpx0
#   # These values will typically be set via Render's environment variables.
#   username: <%= ENV['DATABASE_USERNAME'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>
#   host: <%= ENV['DATABASE_HOST'] %>
#   port: 5432
# 


default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  timeout: 5000
  sslmode: require
  

development:
  <<: *default

test:
  <<: *default

